# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08db2b4ecf0ae5986ba662701e24532044f09b50748de3274e40ff81fba913e475ad4d093fce4d99614931dd3ea647028a93da5391b2092028ee918968088ebe

test:
  secret_key_base: 43f9be5e8f18fe70f30fb9d1309d00866ec29736aea210a25a3efb7a1ff137a0e7672a27dfd7b910e6e651c17ccd9a3ee34a3747e89a8b56ce80a80b12ff37c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
